trigger:
  - master

pool:
  name: 'Default'  # Use your self-hosted agent pool

steps:
  # Step: Build with Maven using the specified JDK
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  # Step: Copy .war files
  - task: CopyFiles@2
    inputs:
      Contents: '**/*.war'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Step: Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'warfile'
      publishLocation: 'Container'
